# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/win10/Documents/C/SCPI/FPGA_RISC_V_Test/FPGA_Project/Risc_V_SCPI_FPGA_Test/Risc_V_SCPI_FPGA_Test.srcs/sources_1/bd/main/ip/main_microblaze_riscv_0_0/main_microblaze_riscv_0_0.xci
# IP: The module: 'main_microblaze_riscv_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/win10/Documents/C/SCPI/FPGA_RISC_V_Test/FPGA_Project/Risc_V_SCPI_FPGA_Test/Risc_V_SCPI_FPGA_Test.gen/sources_1/bd/main/ip/main_microblaze_riscv_0_0/main_microblaze_riscv_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_microblaze_riscv_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/win10/Documents/C/SCPI/FPGA_RISC_V_Test/FPGA_Project/Risc_V_SCPI_FPGA_Test/Risc_V_SCPI_FPGA_Test.gen/sources_1/bd/main/ip/main_microblaze_riscv_0_0/main_microblaze_riscv_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_microblaze_riscv_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/win10/Documents/C/SCPI/FPGA_RISC_V_Test/FPGA_Project/Risc_V_SCPI_FPGA_Test/Risc_V_SCPI_FPGA_Test.gen/sources_1/bd/main/ip/main_microblaze_riscv_0_0/main_microblaze_riscv_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_microblaze_riscv_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/win10/Documents/C/SCPI/FPGA_RISC_V_Test/FPGA_Project/Risc_V_SCPI_FPGA_Test/Risc_V_SCPI_FPGA_Test.srcs/sources_1/bd/main/ip/main_microblaze_riscv_0_0/main_microblaze_riscv_0_0.xci
# IP: The module: 'main_microblaze_riscv_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/win10/Documents/C/SCPI/FPGA_RISC_V_Test/FPGA_Project/Risc_V_SCPI_FPGA_Test/Risc_V_SCPI_FPGA_Test.gen/sources_1/bd/main/ip/main_microblaze_riscv_0_0/main_microblaze_riscv_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_microblaze_riscv_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/win10/Documents/C/SCPI/FPGA_RISC_V_Test/FPGA_Project/Risc_V_SCPI_FPGA_Test/Risc_V_SCPI_FPGA_Test.gen/sources_1/bd/main/ip/main_microblaze_riscv_0_0/main_microblaze_riscv_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_microblaze_riscv_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/win10/Documents/C/SCPI/FPGA_RISC_V_Test/FPGA_Project/Risc_V_SCPI_FPGA_Test/Risc_V_SCPI_FPGA_Test.gen/sources_1/bd/main/ip/main_microblaze_riscv_0_0/main_microblaze_riscv_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_microblaze_riscv_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
