# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/A7_lite_constrains.xdc

# Block Designs: bd/main/main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_xlslice_0_2/main_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xlslice_0_2 || ORIG_REF_NAME==main_xlslice_0_2} -quiet] -quiet

# IP: bd/main/ip/main_xlslice_0_3/main_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xlslice_0_3 || ORIG_REF_NAME==main_xlslice_0_3} -quiet] -quiet

# IP: bd/main/ip/main_xlconcat_0_1/main_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xlconcat_0_1 || ORIG_REF_NAME==main_xlconcat_0_1} -quiet] -quiet

# IP: bd/main/ip/main_microblaze_riscv_0_0/main_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_microblaze_riscv_0_0 || ORIG_REF_NAME==main_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_gpio_0_0/main_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_gpio_0_0 || ORIG_REF_NAME==main_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_uartlite_0_0/main_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_uartlite_0_0 || ORIG_REF_NAME==main_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/main/ip/main_dlmb_v10_0/main_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dlmb_v10_0 || ORIG_REF_NAME==main_dlmb_v10_0} -quiet] -quiet

# IP: bd/main/ip/main_ilmb_v10_0/main_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_ilmb_v10_0 || ORIG_REF_NAME==main_ilmb_v10_0} -quiet] -quiet

# IP: bd/main/ip/main_dlmb_bram_if_cntlr_0/main_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==main_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/main/ip/main_ilmb_bram_if_cntlr_0/main_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==main_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/main/ip/main_lmb_bram_0/main_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_lmb_bram_0 || ORIG_REF_NAME==main_lmb_bram_0} -quiet] -quiet

# IP: bd/main/ip/main_mdm_1_0/main_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_mdm_1_0 || ORIG_REF_NAME==main_mdm_1_0} -quiet] -quiet

# IP: bd/main/ip/main_clk_wiz_1_0/main_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_clk_wiz_1_0 || ORIG_REF_NAME==main_clk_wiz_1_0} -quiet] -quiet

# IP: bd/main/ip/main_rst_clk_wiz_1_100M_0/main_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==main_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_smc_0/main_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_smc_0 || ORIG_REF_NAME==main_axi_smc_0} -quiet] -quiet

# IP: bd/main/ip/main_xlconstant_0_0/main_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xlconstant_0_0 || ORIG_REF_NAME==main_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/win10/Documents/C/SCPI/FPGA_RISC_V_Test/FPGA_Project/Risc_V_SCPI_FPGA_Test/Risc_V_SCPI_FPGA_Test.gen/sources_1/bd/main/main_ooc.xdc
